variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonarcloud-check:
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=glpat-tFz5nGrs2fHrrCPsxsQ_
  only:
    - develop



docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    
  script:
    - docker build -t $CI_REGISTRY_USER/ms-menurestaurant:latest .
    - docker push $CI_REGISTRY_USER/ms-menurestaurant:latest

